server:
  port: 17000

datasource:
  app:
    jdbc-url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

spring:
  flyway:
    enabled: true
    schemas: app
  docker:
    compose:
      lifecycle-management: start_only