server:
  port: 17000

datasource:
  app:
    jdbc-url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

spring:
  flyway:
    enabled: true
    schemas: app
    locations: classpath:BOOT-INF/classes/migration
  docker:
    compose:
      lifecycle-management: none